language: node_js
node_js:
  - "lts/*"

cache:
  directories:
    - "node_modules"

branches:
  only:
  - master

install:
  - yarn install
  - yarn run generate:gh-pages

script:
  - yarn run lint

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  target-branch: gh-pages
  local-dir: dist
  on:
    branch: master
