language: node_js
node_js:
  - "lts/*"

cache:
  directories:
    - "node_modules"

branches:
  only:
  - master

install:
  - yarn install
  - yarn run generate:gh-pages

script:
  - echo "Skipping tests"

# deploy:
#   provider: pages
#   skip-cleanup: true
#   github-token:
#   target-branch: gh-pages
#   local-dir: dist
#   on:
#     branch: master
