name: Build
on:
  push:
    paths-ignore:
      - .github/**
      - .vscode/**
      - "**/.gitignore"
      - .travis.yml
      - "*.md"
      - LICENSE*
    branches:
      - master
      - main
  pull_request:
    types:
      - opened
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: lts/*
          cache: yarn
      - uses: actions/cache@v3
        id: node_modules_cache_id
        env:
          cache-name: cache-node-modules
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
      - name: Install packages
        run: yarn install
        if: ${{ steps.node_modules_cache_id.outputs.cache-hit != 'true' }}
      - name: Lint
        run: yarn run lint
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: lts/*
          cache: yarn
      - uses: actions/cache@v3
        id: node_modules_cache_id
        env:
          cache-name: cache-node-modules
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
      - name: Install packages
        run: yarn install
        if: ${{ steps.node_modules_cache_id.outputs.cache-hit != 'true' }}
      - name: Generate pages
        run: yarn run generate:gh-pages
      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: generated-pages
          path: |
            dist
    needs: lint
  deploy:
    runs-on: ubuntu-latest
    needs:
      - build
      - lint
    steps:
      - uses: actions/checkout@v3
      - name: Archive production artifacts
        uses: actions/download-artifact@v3
        with:
          name: generated-pages
          path: |
            dist
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
    if: github.event_name == 'push'
